version: "3"
services:
  app:
    container_name: myapp
    build: ./app
    command: python app.py --reload
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    container_name: mydb
    image: mysql
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data:/var/lib/mysql


      